/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "Fifo_synth.v:6" *)
module Fifo_synth(clk, reset, wr_enable_synth, rd_enable_synth, FIFO_data_in, pop, push, full_fifo_synth, empty_fifo, almost_empty_fifo, almost_full_fifo_synth, error, FIFO_data_out_synth);
  (* src = "Fifo_synth.v:118" *)
  wire _000_;
  (* src = "Fifo_synth.v:118" *)
  wire _001_;
  (* src = "Fifo_synth.v:73" *)
  wire [2:0] _002_;
  (* src = "Fifo_synth.v:46" *)
  wire _003_;
  (* src = "Fifo_synth.v:46" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "Fifo_synth.v:11" *)
  input [9:0] FIFO_data_in;
  (* src = "Fifo_synth.v:21" *)
  output [9:0] FIFO_data_out_synth;
  (* src = "Fifo_synth.v:16" *)
  output almost_empty_fifo;
  (* src = "Fifo_synth.v:17" *)
  output almost_full_fifo_synth;
  (* src = "Fifo_synth.v:9" *)
  input clk;
  (* src = "Fifo_synth.v:25" *)
  wire [2:0] cnt;
  (* src = "Fifo_synth.v:15" *)
  output empty_fifo;
  (* src = "Fifo_synth.v:18" *)
  output error;
  (* src = "Fifo_synth.v:14" *)
  output full_fifo_synth;
  (* src = "Fifo_synth.v:12" *)
  input pop;
  (* src = "Fifo_synth.v:12" *)
  input push;
  (* src = "Fifo_synth.v:10" *)
  output rd_enable_synth;
  (* src = "Fifo_synth.v:9" *)
  input reset;
  (* src = "Fifo_synth.v:10" *)
  output wr_enable_synth;
  NOT _047_ (
    .A(cnt[2]),
    .Y(_005_)
  );
  NOT _048_ (
    .A(cnt[1]),
    .Y(_006_)
  );
  NOT _049_ (
    .A(cnt[0]),
    .Y(_007_)
  );
  NOT _050_ (
    .A(wr_enable_synth),
    .Y(_008_)
  );
  NOT _051_ (
    .A(rd_enable_synth),
    .Y(_009_)
  );
  NOT _052_ (
    .A(pop),
    .Y(_010_)
  );
  NOT _053_ (
    .A(push),
    .Y(_011_)
  );
  NOR _054_ (
    .A(_007_),
    .B(rd_enable_synth),
    .Y(_012_)
  );
  NAND _055_ (
    .A(cnt[0]),
    .B(_009_),
    .Y(_013_)
  );
  NOR _056_ (
    .A(_006_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _057_ (
    .A(cnt[1]),
    .B(_012_),
    .Y(_015_)
  );
  NAND _058_ (
    .A(_006_),
    .B(_013_),
    .Y(_016_)
  );
  NAND _059_ (
    .A(wr_enable_synth),
    .B(_016_),
    .Y(_017_)
  );
  NOR _060_ (
    .A(_014_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _061_ (
    .A(cnt[0]),
    .B(_009_),
    .Y(_019_)
  );
  NAND _062_ (
    .A(_007_),
    .B(rd_enable_synth),
    .Y(_020_)
  );
  NOR _063_ (
    .A(cnt[1]),
    .B(wr_enable_synth),
    .Y(_021_)
  );
  NOT _064_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _065_ (
    .A(_020_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _066_ (
    .A(cnt[2]),
    .B(_023_),
    .Y(_024_)
  );
  NAND _067_ (
    .A(cnt[2]),
    .B(cnt[1]),
    .Y(_025_)
  );
  NOR _068_ (
    .A(_013_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _069_ (
    .A(cnt[2]),
    .B(_014_),
    .Y(_027_)
  );
  NAND _070_ (
    .A(cnt[1]),
    .B(_008_),
    .Y(_028_)
  );
  NOR _071_ (
    .A(_019_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _072_ (
    .A(_026_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _073_ (
    .A(cnt[2]),
    .B(cnt[1]),
    .Y(_031_)
  );
  NAND _074_ (
    .A(_024_),
    .B(_030_),
    .Y(_032_)
  );
  NOR _075_ (
    .A(_018_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _076_ (
    .A(reset),
    .B(_033_),
    .Y(_002_[1])
  );
  NAND _077_ (
    .A(_007_),
    .B(_031_),
    .Y(_034_)
  );
  NOR _078_ (
    .A(_012_),
    .B(_019_),
    .Y(_035_)
  );
  NAND _079_ (
    .A(_013_),
    .B(_020_),
    .Y(_036_)
  );
  NAND _080_ (
    .A(_034_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _081_ (
    .A(wr_enable_synth),
    .B(_037_),
    .Y(_038_)
  );
  NAND _082_ (
    .A(wr_enable_synth),
    .B(_035_),
    .Y(_039_)
  );
  NAND _083_ (
    .A(_027_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _084_ (
    .A(_038_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _085_ (
    .A(reset),
    .B(_041_),
    .Y(_002_[0])
  );
  NOR _086_ (
    .A(cnt[0]),
    .B(_025_),
    .Y(_001_)
  );
  NAND _087_ (
    .A(cnt[0]),
    .B(_031_),
    .Y(_042_)
  );
  NOT _088_ (
    .A(_042_),
    .Y(_000_)
  );
  NOR _089_ (
    .A(_005_),
    .B(_023_),
    .Y(_043_)
  );
  NOR _090_ (
    .A(cnt[2]),
    .B(wr_enable_synth),
    .Y(_044_)
  );
  NOR _091_ (
    .A(_015_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _092_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _093_ (
    .A(reset),
    .B(_046_),
    .Y(_002_[2])
  );
  NOR _094_ (
    .A(reset),
    .B(_010_),
    .Y(_003_)
  );
  NOR _095_ (
    .A(reset),
    .B(_011_),
    .Y(_004_)
  );
  (* src = "Fifo_synth.v:118" *)
  DFF _096_ (
    .C(clk),
    .D(_000_),
    .Q(almost_empty_fifo)
  );
  (* src = "Fifo_synth.v:118" *)
  DFF _097_ (
    .C(clk),
    .D(_001_),
    .Q(almost_full_fifo_synth)
  );
  (* src = "Fifo_synth.v:73" *)
  DFF _098_ (
    .C(clk),
    .D(_002_[0]),
    .Q(cnt[0])
  );
  (* src = "Fifo_synth.v:73" *)
  DFF _099_ (
    .C(clk),
    .D(_002_[1]),
    .Q(cnt[1])
  );
  (* src = "Fifo_synth.v:73" *)
  DFF _100_ (
    .C(clk),
    .D(_002_[2]),
    .Q(cnt[2])
  );
  (* src = "Fifo_synth.v:46" *)
  DFF _101_ (
    .C(clk),
    .D(_004_),
    .Q(wr_enable_synth)
  );
  (* src = "Fifo_synth.v:46" *)
  DFF _102_ (
    .C(clk),
    .D(_003_),
    .Q(rd_enable_synth)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Fifo_synth.v:42" *)
  memoria mem (
    .clk(clk),
    .memo_data_in(FIFO_data_in),
    .memo_data_out(FIFO_data_out_synth),
    .rdmem_enable(rd_enable_synth),
    .reset(reset),
    .wrmem_enable(wr_enable_synth)
  );
  assign empty_fifo = 1'h0;
  assign full_fifo_synth = 1'h0;
endmodule
