/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador.v:13" *)
module contador_s(clk, reset, idx, req, pop_F0, pop_F1, pop_F2, pop_F3, IDLE, empty_P4, empty_P5, empty_P6, empty_P7, valid_contador_s, contador_out_s);
  (* src = "contador.v:63" *)
  wire [9:0] _000_;
  (* src = "contador.v:63" *)
  wire [9:0] _001_;
  (* src = "contador.v:63" *)
  wire [9:0] _002_;
  (* src = "contador.v:63" *)
  wire [9:0] _003_;
  (* src = "contador.v:63" *)
  wire [4:0] _004_;
  (* src = "contador.v:63" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  (* src = "contador.v:31" *)
  input IDLE;
  (* src = "contador.v:22" *)
  input clk;
  (* src = "contador.v:53" *)
  wire [9:0] contador_fifo0;
  (* src = "contador.v:54" *)
  wire [9:0] contador_fifo1;
  (* src = "contador.v:55" *)
  wire [9:0] contador_fifo2;
  (* src = "contador.v:56" *)
  wire [9:0] contador_fifo3;
  (* src = "contador.v:39" *)
  output [4:0] contador_out_s;
  (* src = "contador.v:32" *)
  input empty_P4;
  (* src = "contador.v:33" *)
  input empty_P5;
  (* src = "contador.v:34" *)
  input empty_P6;
  (* src = "contador.v:35" *)
  input empty_P7;
  (* src = "contador.v:24" *)
  input [1:0] idx;
  (* src = "contador.v:26" *)
  input pop_F0;
  (* src = "contador.v:27" *)
  input pop_F1;
  (* src = "contador.v:28" *)
  input pop_F2;
  (* src = "contador.v:29" *)
  input pop_F3;
  (* src = "contador.v:25" *)
  input req;
  (* src = "contador.v:23" *)
  input reset;
  (* src = "contador.v:38" *)
  output valid_contador_s;
  NOT _289_ (
    .A(contador_fifo3[9]),
    .Y(_006_)
  );
  NOT _290_ (
    .A(contador_fifo3[8]),
    .Y(_007_)
  );
  NOT _291_ (
    .A(contador_fifo3[7]),
    .Y(_008_)
  );
  NOT _292_ (
    .A(contador_fifo3[6]),
    .Y(_009_)
  );
  NOT _293_ (
    .A(contador_fifo3[5]),
    .Y(_010_)
  );
  NOT _294_ (
    .A(contador_fifo3[4]),
    .Y(_011_)
  );
  NOT _295_ (
    .A(contador_fifo3[3]),
    .Y(_012_)
  );
  NOT _296_ (
    .A(contador_fifo3[2]),
    .Y(_013_)
  );
  NOT _297_ (
    .A(contador_fifo3[1]),
    .Y(_014_)
  );
  NOT _298_ (
    .A(contador_fifo3[0]),
    .Y(_015_)
  );
  NOT _299_ (
    .A(contador_fifo2[9]),
    .Y(_016_)
  );
  NOT _300_ (
    .A(contador_fifo2[8]),
    .Y(_017_)
  );
  NOT _301_ (
    .A(contador_fifo2[7]),
    .Y(_018_)
  );
  NOT _302_ (
    .A(contador_fifo2[6]),
    .Y(_019_)
  );
  NOT _303_ (
    .A(contador_fifo2[5]),
    .Y(_020_)
  );
  NOT _304_ (
    .A(contador_fifo2[4]),
    .Y(_021_)
  );
  NOT _305_ (
    .A(contador_fifo2[3]),
    .Y(_022_)
  );
  NOT _306_ (
    .A(contador_fifo2[2]),
    .Y(_023_)
  );
  NOT _307_ (
    .A(contador_fifo2[1]),
    .Y(_024_)
  );
  NOT _308_ (
    .A(contador_fifo2[0]),
    .Y(_025_)
  );
  NOT _309_ (
    .A(contador_fifo1[9]),
    .Y(_026_)
  );
  NOT _310_ (
    .A(contador_fifo1[8]),
    .Y(_027_)
  );
  NOT _311_ (
    .A(contador_fifo1[7]),
    .Y(_028_)
  );
  NOT _312_ (
    .A(contador_fifo1[6]),
    .Y(_029_)
  );
  NOT _313_ (
    .A(contador_fifo1[5]),
    .Y(_030_)
  );
  NOT _314_ (
    .A(contador_fifo1[4]),
    .Y(_031_)
  );
  NOT _315_ (
    .A(contador_fifo1[3]),
    .Y(_032_)
  );
  NOT _316_ (
    .A(contador_fifo1[2]),
    .Y(_033_)
  );
  NOT _317_ (
    .A(contador_fifo1[1]),
    .Y(_034_)
  );
  NOT _318_ (
    .A(contador_fifo1[0]),
    .Y(_035_)
  );
  NOT _319_ (
    .A(contador_fifo0[9]),
    .Y(_036_)
  );
  NOT _320_ (
    .A(contador_fifo0[8]),
    .Y(_037_)
  );
  NOT _321_ (
    .A(contador_fifo0[7]),
    .Y(_038_)
  );
  NOT _322_ (
    .A(contador_fifo0[6]),
    .Y(_039_)
  );
  NOT _323_ (
    .A(contador_fifo0[5]),
    .Y(_040_)
  );
  NOT _324_ (
    .A(contador_fifo0[4]),
    .Y(_041_)
  );
  NOT _325_ (
    .A(contador_fifo0[3]),
    .Y(_042_)
  );
  NOT _326_ (
    .A(contador_fifo0[2]),
    .Y(_043_)
  );
  NOT _327_ (
    .A(contador_fifo0[1]),
    .Y(_044_)
  );
  NOT _328_ (
    .A(contador_fifo0[0]),
    .Y(_045_)
  );
  NOT _329_ (
    .A(idx[1]),
    .Y(_046_)
  );
  NOT _330_ (
    .A(idx[0]),
    .Y(_047_)
  );
  NOT _331_ (
    .A(IDLE),
    .Y(_048_)
  );
  NOT _332_ (
    .A(req),
    .Y(_049_)
  );
  NOT _333_ (
    .A(empty_P7),
    .Y(_050_)
  );
  NOT _334_ (
    .A(pop_F3),
    .Y(_051_)
  );
  NOT _335_ (
    .A(empty_P6),
    .Y(_052_)
  );
  NOT _336_ (
    .A(pop_F2),
    .Y(_053_)
  );
  NOT _337_ (
    .A(empty_P5),
    .Y(_054_)
  );
  NOT _338_ (
    .A(pop_F1),
    .Y(_055_)
  );
  NOT _339_ (
    .A(empty_P4),
    .Y(_056_)
  );
  NOT _340_ (
    .A(pop_F0),
    .Y(_057_)
  );
  NOT _341_ (
    .A(reset),
    .Y(_058_)
  );
  NOT _342_ (
    .A(valid_contador_s),
    .Y(_059_)
  );
  NOR _343_ (
    .A(_048_),
    .B(_049_),
    .Y(_060_)
  );
  NOR _344_ (
    .A(idx[1]),
    .B(idx[0]),
    .Y(_061_)
  );
  NAND _345_ (
    .A(contador_fifo0[3]),
    .B(_061_),
    .Y(_062_)
  );
  NOR _346_ (
    .A(idx[1]),
    .B(_047_),
    .Y(_063_)
  );
  NAND _347_ (
    .A(contador_fifo1[3]),
    .B(_063_),
    .Y(_064_)
  );
  NAND _348_ (
    .A(_062_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _349_ (
    .A(_046_),
    .B(_047_),
    .Y(_066_)
  );
  NAND _350_ (
    .A(contador_fifo3[3]),
    .B(_066_),
    .Y(_067_)
  );
  NOR _351_ (
    .A(_046_),
    .B(idx[0]),
    .Y(_068_)
  );
  NAND _352_ (
    .A(contador_fifo2[3]),
    .B(_068_),
    .Y(_069_)
  );
  NAND _353_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _354_ (
    .A(_065_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _355_ (
    .A(contador_out_s[3]),
    .B(_060_),
    .Y(_072_)
  );
  NAND _356_ (
    .A(_060_),
    .B(_071_),
    .Y(_073_)
  );
  NAND _357_ (
    .A(_058_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _358_ (
    .A(_072_),
    .B(_074_),
    .Y(_004_[3])
  );
  NAND _359_ (
    .A(contador_fifo3[2]),
    .B(_066_),
    .Y(_075_)
  );
  NAND _360_ (
    .A(contador_fifo1[2]),
    .B(_063_),
    .Y(_076_)
  );
  NAND _361_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _362_ (
    .A(contador_fifo0[2]),
    .B(_061_),
    .Y(_078_)
  );
  NAND _363_ (
    .A(contador_fifo2[2]),
    .B(_068_),
    .Y(_079_)
  );
  NAND _364_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _365_ (
    .A(_077_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _366_ (
    .A(contador_out_s[2]),
    .B(_060_),
    .Y(_082_)
  );
  NOR _367_ (
    .A(reset),
    .B(_082_),
    .Y(_083_)
  );
  NAND _368_ (
    .A(_060_),
    .B(_081_),
    .Y(_084_)
  );
  NAND _369_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NOT _370_ (
    .A(_085_),
    .Y(_004_[2])
  );
  NAND _371_ (
    .A(contador_fifo3[1]),
    .B(_066_),
    .Y(_086_)
  );
  NAND _372_ (
    .A(contador_fifo1[1]),
    .B(_063_),
    .Y(_087_)
  );
  NAND _373_ (
    .A(_086_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _374_ (
    .A(contador_fifo0[1]),
    .B(_061_),
    .Y(_089_)
  );
  NAND _375_ (
    .A(contador_fifo2[1]),
    .B(_068_),
    .Y(_090_)
  );
  NAND _376_ (
    .A(_089_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _377_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _378_ (
    .A(contador_out_s[1]),
    .B(_060_),
    .Y(_093_)
  );
  NAND _379_ (
    .A(_060_),
    .B(_092_),
    .Y(_094_)
  );
  NAND _380_ (
    .A(_058_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _381_ (
    .A(_093_),
    .B(_095_),
    .Y(_004_[1])
  );
  NAND _382_ (
    .A(contador_fifo3[0]),
    .B(_066_),
    .Y(_096_)
  );
  NAND _383_ (
    .A(contador_fifo1[0]),
    .B(_063_),
    .Y(_097_)
  );
  NAND _384_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _385_ (
    .A(contador_fifo0[0]),
    .B(_061_),
    .Y(_099_)
  );
  NAND _386_ (
    .A(contador_fifo2[0]),
    .B(_068_),
    .Y(_100_)
  );
  NAND _387_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _388_ (
    .A(_098_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _389_ (
    .A(contador_out_s[0]),
    .B(_060_),
    .Y(_103_)
  );
  NAND _390_ (
    .A(_060_),
    .B(_102_),
    .Y(_104_)
  );
  NAND _391_ (
    .A(_058_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _392_ (
    .A(_103_),
    .B(_105_),
    .Y(_004_[0])
  );
  NOR _393_ (
    .A(empty_P4),
    .B(_057_),
    .Y(_106_)
  );
  NAND _394_ (
    .A(_056_),
    .B(pop_F0),
    .Y(_107_)
  );
  NOR _395_ (
    .A(_045_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _396_ (
    .A(contador_fifo0[0]),
    .B(_106_),
    .Y(_109_)
  );
  NOR _397_ (
    .A(_044_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _398_ (
    .A(contador_fifo0[1]),
    .B(_108_),
    .Y(_111_)
  );
  NOR _399_ (
    .A(_043_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _400_ (
    .A(contador_fifo0[2]),
    .B(_110_),
    .Y(_113_)
  );
  NOR _401_ (
    .A(_042_),
    .B(_113_),
    .Y(_114_)
  );
  NAND _402_ (
    .A(contador_fifo0[3]),
    .B(_112_),
    .Y(_115_)
  );
  NOR _403_ (
    .A(_041_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _404_ (
    .A(contador_fifo0[4]),
    .B(_114_),
    .Y(_117_)
  );
  NOR _405_ (
    .A(_040_),
    .B(_117_),
    .Y(_118_)
  );
  NAND _406_ (
    .A(contador_fifo0[5]),
    .B(_116_),
    .Y(_119_)
  );
  NOR _407_ (
    .A(_039_),
    .B(_119_),
    .Y(_120_)
  );
  NAND _408_ (
    .A(contador_fifo0[6]),
    .B(_118_),
    .Y(_121_)
  );
  NOR _409_ (
    .A(_038_),
    .B(_121_),
    .Y(_122_)
  );
  NAND _410_ (
    .A(contador_fifo0[7]),
    .B(_120_),
    .Y(_123_)
  );
  NOR _411_ (
    .A(_037_),
    .B(_123_),
    .Y(_124_)
  );
  NAND _412_ (
    .A(contador_fifo0[8]),
    .B(_122_),
    .Y(_125_)
  );
  NOR _413_ (
    .A(contador_fifo0[8]),
    .B(_122_),
    .Y(_126_)
  );
  NOR _414_ (
    .A(reset),
    .B(_126_),
    .Y(_127_)
  );
  NOT _415_ (
    .A(_127_),
    .Y(_128_)
  );
  NOR _416_ (
    .A(_124_),
    .B(_128_),
    .Y(_000_[8])
  );
  NAND _417_ (
    .A(_038_),
    .B(_121_),
    .Y(_129_)
  );
  NAND _418_ (
    .A(_058_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _419_ (
    .A(_122_),
    .B(_130_),
    .Y(_000_[7])
  );
  NAND _420_ (
    .A(_039_),
    .B(_119_),
    .Y(_131_)
  );
  NAND _421_ (
    .A(_058_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _422_ (
    .A(_120_),
    .B(_132_),
    .Y(_000_[6])
  );
  NAND _423_ (
    .A(_040_),
    .B(_117_),
    .Y(_133_)
  );
  NAND _424_ (
    .A(_058_),
    .B(_133_),
    .Y(_134_)
  );
  NOR _425_ (
    .A(_118_),
    .B(_134_),
    .Y(_000_[5])
  );
  NAND _426_ (
    .A(_041_),
    .B(_115_),
    .Y(_135_)
  );
  NAND _427_ (
    .A(_058_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _428_ (
    .A(_116_),
    .B(_136_),
    .Y(_000_[4])
  );
  NAND _429_ (
    .A(_042_),
    .B(_113_),
    .Y(_137_)
  );
  NAND _430_ (
    .A(_058_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _431_ (
    .A(_114_),
    .B(_138_),
    .Y(_000_[3])
  );
  NAND _432_ (
    .A(_043_),
    .B(_111_),
    .Y(_139_)
  );
  NAND _433_ (
    .A(_058_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _434_ (
    .A(_112_),
    .B(_140_),
    .Y(_000_[2])
  );
  NAND _435_ (
    .A(_044_),
    .B(_109_),
    .Y(_141_)
  );
  NAND _436_ (
    .A(_058_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _437_ (
    .A(_110_),
    .B(_142_),
    .Y(_000_[1])
  );
  NAND _438_ (
    .A(_045_),
    .B(_107_),
    .Y(_143_)
  );
  NAND _439_ (
    .A(_058_),
    .B(_143_),
    .Y(_144_)
  );
  NOR _440_ (
    .A(_108_),
    .B(_144_),
    .Y(_000_[0])
  );
  NOR _441_ (
    .A(empty_P5),
    .B(_055_),
    .Y(_145_)
  );
  NAND _442_ (
    .A(_054_),
    .B(pop_F1),
    .Y(_146_)
  );
  NOR _443_ (
    .A(_035_),
    .B(_146_),
    .Y(_147_)
  );
  NAND _444_ (
    .A(contador_fifo1[0]),
    .B(_145_),
    .Y(_148_)
  );
  NOR _445_ (
    .A(_034_),
    .B(_148_),
    .Y(_149_)
  );
  NAND _446_ (
    .A(contador_fifo1[1]),
    .B(_147_),
    .Y(_150_)
  );
  NOR _447_ (
    .A(_033_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _448_ (
    .A(contador_fifo1[2]),
    .B(_149_),
    .Y(_152_)
  );
  NOR _449_ (
    .A(_032_),
    .B(_152_),
    .Y(_153_)
  );
  NAND _450_ (
    .A(contador_fifo1[3]),
    .B(_151_),
    .Y(_154_)
  );
  NOR _451_ (
    .A(_031_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _452_ (
    .A(contador_fifo1[4]),
    .B(_153_),
    .Y(_156_)
  );
  NOR _453_ (
    .A(_030_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _454_ (
    .A(contador_fifo1[5]),
    .B(_155_),
    .Y(_158_)
  );
  NOR _455_ (
    .A(_029_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _456_ (
    .A(contador_fifo1[6]),
    .B(_157_),
    .Y(_160_)
  );
  NOR _457_ (
    .A(_028_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _458_ (
    .A(contador_fifo1[7]),
    .B(_159_),
    .Y(_162_)
  );
  NOR _459_ (
    .A(_027_),
    .B(_162_),
    .Y(_163_)
  );
  NAND _460_ (
    .A(contador_fifo1[8]),
    .B(_161_),
    .Y(_164_)
  );
  NOR _461_ (
    .A(contador_fifo1[8]),
    .B(_161_),
    .Y(_165_)
  );
  NOR _462_ (
    .A(reset),
    .B(_165_),
    .Y(_166_)
  );
  NOT _463_ (
    .A(_166_),
    .Y(_167_)
  );
  NOR _464_ (
    .A(_163_),
    .B(_167_),
    .Y(_001_[8])
  );
  NAND _465_ (
    .A(_028_),
    .B(_160_),
    .Y(_168_)
  );
  NAND _466_ (
    .A(_058_),
    .B(_168_),
    .Y(_169_)
  );
  NOR _467_ (
    .A(_161_),
    .B(_169_),
    .Y(_001_[7])
  );
  NAND _468_ (
    .A(_029_),
    .B(_158_),
    .Y(_170_)
  );
  NAND _469_ (
    .A(_058_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _470_ (
    .A(_159_),
    .B(_171_),
    .Y(_001_[6])
  );
  NAND _471_ (
    .A(_030_),
    .B(_156_),
    .Y(_172_)
  );
  NAND _472_ (
    .A(_058_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _473_ (
    .A(_157_),
    .B(_173_),
    .Y(_001_[5])
  );
  NAND _474_ (
    .A(_031_),
    .B(_154_),
    .Y(_174_)
  );
  NAND _475_ (
    .A(_058_),
    .B(_174_),
    .Y(_175_)
  );
  NOR _476_ (
    .A(_155_),
    .B(_175_),
    .Y(_001_[4])
  );
  NAND _477_ (
    .A(_032_),
    .B(_152_),
    .Y(_176_)
  );
  NAND _478_ (
    .A(_058_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _479_ (
    .A(_153_),
    .B(_177_),
    .Y(_001_[3])
  );
  NAND _480_ (
    .A(_033_),
    .B(_150_),
    .Y(_178_)
  );
  NAND _481_ (
    .A(_058_),
    .B(_178_),
    .Y(_179_)
  );
  NOR _482_ (
    .A(_151_),
    .B(_179_),
    .Y(_001_[2])
  );
  NAND _483_ (
    .A(_034_),
    .B(_148_),
    .Y(_180_)
  );
  NAND _484_ (
    .A(_058_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _485_ (
    .A(_149_),
    .B(_181_),
    .Y(_001_[1])
  );
  NAND _486_ (
    .A(_035_),
    .B(_146_),
    .Y(_182_)
  );
  NAND _487_ (
    .A(_058_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _488_ (
    .A(_147_),
    .B(_183_),
    .Y(_001_[0])
  );
  NOR _489_ (
    .A(empty_P6),
    .B(_053_),
    .Y(_184_)
  );
  NAND _490_ (
    .A(_052_),
    .B(pop_F2),
    .Y(_185_)
  );
  NOR _491_ (
    .A(_025_),
    .B(_185_),
    .Y(_186_)
  );
  NAND _492_ (
    .A(contador_fifo2[0]),
    .B(_184_),
    .Y(_187_)
  );
  NOR _493_ (
    .A(_024_),
    .B(_187_),
    .Y(_188_)
  );
  NAND _494_ (
    .A(contador_fifo2[1]),
    .B(_186_),
    .Y(_189_)
  );
  NOR _495_ (
    .A(_023_),
    .B(_189_),
    .Y(_190_)
  );
  NAND _496_ (
    .A(contador_fifo2[2]),
    .B(_188_),
    .Y(_191_)
  );
  NOR _497_ (
    .A(_022_),
    .B(_191_),
    .Y(_192_)
  );
  NAND _498_ (
    .A(contador_fifo2[3]),
    .B(_190_),
    .Y(_193_)
  );
  NOR _499_ (
    .A(_021_),
    .B(_193_),
    .Y(_194_)
  );
  NAND _500_ (
    .A(contador_fifo2[4]),
    .B(_192_),
    .Y(_195_)
  );
  NOR _501_ (
    .A(_020_),
    .B(_195_),
    .Y(_196_)
  );
  NAND _502_ (
    .A(contador_fifo2[5]),
    .B(_194_),
    .Y(_197_)
  );
  NOR _503_ (
    .A(_019_),
    .B(_197_),
    .Y(_198_)
  );
  NAND _504_ (
    .A(contador_fifo2[6]),
    .B(_196_),
    .Y(_199_)
  );
  NOR _505_ (
    .A(_018_),
    .B(_199_),
    .Y(_200_)
  );
  NAND _506_ (
    .A(contador_fifo2[7]),
    .B(_198_),
    .Y(_201_)
  );
  NOR _507_ (
    .A(_017_),
    .B(_201_),
    .Y(_202_)
  );
  NAND _508_ (
    .A(contador_fifo2[8]),
    .B(_200_),
    .Y(_203_)
  );
  NOR _509_ (
    .A(contador_fifo2[8]),
    .B(_200_),
    .Y(_204_)
  );
  NOR _510_ (
    .A(reset),
    .B(_204_),
    .Y(_205_)
  );
  NOT _511_ (
    .A(_205_),
    .Y(_206_)
  );
  NOR _512_ (
    .A(_202_),
    .B(_206_),
    .Y(_002_[8])
  );
  NAND _513_ (
    .A(_018_),
    .B(_199_),
    .Y(_207_)
  );
  NAND _514_ (
    .A(_058_),
    .B(_207_),
    .Y(_208_)
  );
  NOR _515_ (
    .A(_200_),
    .B(_208_),
    .Y(_002_[7])
  );
  NAND _516_ (
    .A(_019_),
    .B(_197_),
    .Y(_209_)
  );
  NAND _517_ (
    .A(_058_),
    .B(_209_),
    .Y(_210_)
  );
  NOR _518_ (
    .A(_198_),
    .B(_210_),
    .Y(_002_[6])
  );
  NAND _519_ (
    .A(_020_),
    .B(_195_),
    .Y(_211_)
  );
  NAND _520_ (
    .A(_058_),
    .B(_211_),
    .Y(_212_)
  );
  NOR _521_ (
    .A(_196_),
    .B(_212_),
    .Y(_002_[5])
  );
  NAND _522_ (
    .A(_021_),
    .B(_193_),
    .Y(_213_)
  );
  NAND _523_ (
    .A(_058_),
    .B(_213_),
    .Y(_214_)
  );
  NOR _524_ (
    .A(_194_),
    .B(_214_),
    .Y(_002_[4])
  );
  NAND _525_ (
    .A(_022_),
    .B(_191_),
    .Y(_215_)
  );
  NAND _526_ (
    .A(_058_),
    .B(_215_),
    .Y(_216_)
  );
  NOR _527_ (
    .A(_192_),
    .B(_216_),
    .Y(_002_[3])
  );
  NAND _528_ (
    .A(_023_),
    .B(_189_),
    .Y(_217_)
  );
  NAND _529_ (
    .A(_058_),
    .B(_217_),
    .Y(_218_)
  );
  NOR _530_ (
    .A(_190_),
    .B(_218_),
    .Y(_002_[2])
  );
  NAND _531_ (
    .A(_024_),
    .B(_187_),
    .Y(_219_)
  );
  NAND _532_ (
    .A(_058_),
    .B(_219_),
    .Y(_220_)
  );
  NOR _533_ (
    .A(_188_),
    .B(_220_),
    .Y(_002_[1])
  );
  NAND _534_ (
    .A(_025_),
    .B(_185_),
    .Y(_221_)
  );
  NAND _535_ (
    .A(_058_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _536_ (
    .A(_186_),
    .B(_222_),
    .Y(_002_[0])
  );
  NOR _537_ (
    .A(empty_P7),
    .B(_051_),
    .Y(_223_)
  );
  NAND _538_ (
    .A(_050_),
    .B(pop_F3),
    .Y(_224_)
  );
  NOR _539_ (
    .A(_015_),
    .B(_224_),
    .Y(_225_)
  );
  NAND _540_ (
    .A(contador_fifo3[0]),
    .B(_223_),
    .Y(_226_)
  );
  NOR _541_ (
    .A(_014_),
    .B(_226_),
    .Y(_227_)
  );
  NAND _542_ (
    .A(contador_fifo3[1]),
    .B(_225_),
    .Y(_228_)
  );
  NOR _543_ (
    .A(_013_),
    .B(_228_),
    .Y(_229_)
  );
  NAND _544_ (
    .A(contador_fifo3[2]),
    .B(_227_),
    .Y(_230_)
  );
  NOR _545_ (
    .A(_012_),
    .B(_230_),
    .Y(_231_)
  );
  NAND _546_ (
    .A(contador_fifo3[3]),
    .B(_229_),
    .Y(_232_)
  );
  NOR _547_ (
    .A(_011_),
    .B(_232_),
    .Y(_233_)
  );
  NAND _548_ (
    .A(contador_fifo3[4]),
    .B(_231_),
    .Y(_234_)
  );
  NOR _549_ (
    .A(_010_),
    .B(_234_),
    .Y(_235_)
  );
  NAND _550_ (
    .A(contador_fifo3[5]),
    .B(_233_),
    .Y(_236_)
  );
  NOR _551_ (
    .A(_009_),
    .B(_236_),
    .Y(_237_)
  );
  NAND _552_ (
    .A(contador_fifo3[6]),
    .B(_235_),
    .Y(_238_)
  );
  NOR _553_ (
    .A(_008_),
    .B(_238_),
    .Y(_239_)
  );
  NAND _554_ (
    .A(contador_fifo3[7]),
    .B(_237_),
    .Y(_240_)
  );
  NOR _555_ (
    .A(_007_),
    .B(_240_),
    .Y(_241_)
  );
  NAND _556_ (
    .A(contador_fifo3[8]),
    .B(_239_),
    .Y(_242_)
  );
  NOR _557_ (
    .A(contador_fifo3[8]),
    .B(_239_),
    .Y(_243_)
  );
  NOR _558_ (
    .A(reset),
    .B(_243_),
    .Y(_244_)
  );
  NOT _559_ (
    .A(_244_),
    .Y(_245_)
  );
  NOR _560_ (
    .A(_241_),
    .B(_245_),
    .Y(_003_[8])
  );
  NAND _561_ (
    .A(_008_),
    .B(_238_),
    .Y(_246_)
  );
  NAND _562_ (
    .A(_058_),
    .B(_246_),
    .Y(_247_)
  );
  NOR _563_ (
    .A(_239_),
    .B(_247_),
    .Y(_003_[7])
  );
  NAND _564_ (
    .A(_009_),
    .B(_236_),
    .Y(_248_)
  );
  NAND _565_ (
    .A(_058_),
    .B(_248_),
    .Y(_249_)
  );
  NOR _566_ (
    .A(_237_),
    .B(_249_),
    .Y(_003_[6])
  );
  NAND _567_ (
    .A(_010_),
    .B(_234_),
    .Y(_250_)
  );
  NAND _568_ (
    .A(_058_),
    .B(_250_),
    .Y(_251_)
  );
  NOR _569_ (
    .A(_235_),
    .B(_251_),
    .Y(_003_[5])
  );
  NAND _570_ (
    .A(_011_),
    .B(_232_),
    .Y(_252_)
  );
  NAND _571_ (
    .A(_058_),
    .B(_252_),
    .Y(_253_)
  );
  NOR _572_ (
    .A(_233_),
    .B(_253_),
    .Y(_003_[4])
  );
  NAND _573_ (
    .A(_012_),
    .B(_230_),
    .Y(_254_)
  );
  NAND _574_ (
    .A(_058_),
    .B(_254_),
    .Y(_255_)
  );
  NOR _575_ (
    .A(_231_),
    .B(_255_),
    .Y(_003_[3])
  );
  NAND _576_ (
    .A(_013_),
    .B(_228_),
    .Y(_256_)
  );
  NAND _577_ (
    .A(_058_),
    .B(_256_),
    .Y(_257_)
  );
  NOR _578_ (
    .A(_229_),
    .B(_257_),
    .Y(_003_[2])
  );
  NAND _579_ (
    .A(_014_),
    .B(_226_),
    .Y(_258_)
  );
  NAND _580_ (
    .A(_058_),
    .B(_258_),
    .Y(_259_)
  );
  NOR _581_ (
    .A(_227_),
    .B(_259_),
    .Y(_003_[1])
  );
  NAND _582_ (
    .A(_015_),
    .B(_224_),
    .Y(_260_)
  );
  NAND _583_ (
    .A(_058_),
    .B(_260_),
    .Y(_261_)
  );
  NOR _584_ (
    .A(_225_),
    .B(_261_),
    .Y(_003_[0])
  );
  NOR _585_ (
    .A(_006_),
    .B(_241_),
    .Y(_262_)
  );
  NOR _586_ (
    .A(contador_fifo3[9]),
    .B(_242_),
    .Y(_263_)
  );
  NOR _587_ (
    .A(_262_),
    .B(_263_),
    .Y(_264_)
  );
  NOR _588_ (
    .A(reset),
    .B(_264_),
    .Y(_003_[9])
  );
  NOR _589_ (
    .A(_016_),
    .B(_202_),
    .Y(_265_)
  );
  NOR _590_ (
    .A(contador_fifo2[9]),
    .B(_203_),
    .Y(_266_)
  );
  NOR _591_ (
    .A(_265_),
    .B(_266_),
    .Y(_267_)
  );
  NOR _592_ (
    .A(reset),
    .B(_267_),
    .Y(_002_[9])
  );
  NOR _593_ (
    .A(_026_),
    .B(_163_),
    .Y(_268_)
  );
  NOR _594_ (
    .A(contador_fifo1[9]),
    .B(_164_),
    .Y(_269_)
  );
  NOR _595_ (
    .A(_268_),
    .B(_269_),
    .Y(_270_)
  );
  NOR _596_ (
    .A(reset),
    .B(_270_),
    .Y(_001_[9])
  );
  NOR _597_ (
    .A(_036_),
    .B(_124_),
    .Y(_271_)
  );
  NOR _598_ (
    .A(contador_fifo0[9]),
    .B(_125_),
    .Y(_272_)
  );
  NOR _599_ (
    .A(_271_),
    .B(_272_),
    .Y(_273_)
  );
  NOR _600_ (
    .A(reset),
    .B(_273_),
    .Y(_000_[9])
  );
  NAND _601_ (
    .A(contador_fifo3[4]),
    .B(_066_),
    .Y(_274_)
  );
  NAND _602_ (
    .A(contador_fifo1[4]),
    .B(_063_),
    .Y(_275_)
  );
  NAND _603_ (
    .A(_274_),
    .B(_275_),
    .Y(_276_)
  );
  NAND _604_ (
    .A(contador_fifo0[4]),
    .B(_061_),
    .Y(_277_)
  );
  NAND _605_ (
    .A(contador_fifo2[4]),
    .B(_068_),
    .Y(_278_)
  );
  NAND _606_ (
    .A(_277_),
    .B(_278_),
    .Y(_279_)
  );
  NOR _607_ (
    .A(_276_),
    .B(_279_),
    .Y(_280_)
  );
  NOR _608_ (
    .A(contador_out_s[4]),
    .B(_060_),
    .Y(_281_)
  );
  NAND _609_ (
    .A(_060_),
    .B(_280_),
    .Y(_282_)
  );
  NAND _610_ (
    .A(_058_),
    .B(_282_),
    .Y(_283_)
  );
  NOR _611_ (
    .A(_281_),
    .B(_283_),
    .Y(_004_[4])
  );
  NOR _612_ (
    .A(_106_),
    .B(_223_),
    .Y(_284_)
  );
  NAND _613_ (
    .A(_059_),
    .B(_146_),
    .Y(_285_)
  );
  NOR _614_ (
    .A(_184_),
    .B(_285_),
    .Y(_286_)
  );
  NAND _615_ (
    .A(_284_),
    .B(_286_),
    .Y(_287_)
  );
  NOR _616_ (
    .A(_060_),
    .B(_287_),
    .Y(_288_)
  );
  NOR _617_ (
    .A(reset),
    .B(_288_),
    .Y(_005_)
  );
  (* src = "contador.v:63" *)
  DFF _618_ (
    .C(clk),
    .D(_005_),
    .Q(valid_contador_s)
  );
  (* src = "contador.v:63" *)
  DFF _619_ (
    .C(clk),
    .D(_004_[0]),
    .Q(contador_out_s[0])
  );
  (* src = "contador.v:63" *)
  DFF _620_ (
    .C(clk),
    .D(_004_[1]),
    .Q(contador_out_s[1])
  );
  (* src = "contador.v:63" *)
  DFF _621_ (
    .C(clk),
    .D(_004_[2]),
    .Q(contador_out_s[2])
  );
  (* src = "contador.v:63" *)
  DFF _622_ (
    .C(clk),
    .D(_004_[3]),
    .Q(contador_out_s[3])
  );
  (* src = "contador.v:63" *)
  DFF _623_ (
    .C(clk),
    .D(_004_[4]),
    .Q(contador_out_s[4])
  );
  (* src = "contador.v:63" *)
  DFF _624_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador_fifo0[0])
  );
  (* src = "contador.v:63" *)
  DFF _625_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador_fifo0[1])
  );
  (* src = "contador.v:63" *)
  DFF _626_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador_fifo0[2])
  );
  (* src = "contador.v:63" *)
  DFF _627_ (
    .C(clk),
    .D(_000_[3]),
    .Q(contador_fifo0[3])
  );
  (* src = "contador.v:63" *)
  DFF _628_ (
    .C(clk),
    .D(_000_[4]),
    .Q(contador_fifo0[4])
  );
  (* src = "contador.v:63" *)
  DFF _629_ (
    .C(clk),
    .D(_000_[5]),
    .Q(contador_fifo0[5])
  );
  (* src = "contador.v:63" *)
  DFF _630_ (
    .C(clk),
    .D(_000_[6]),
    .Q(contador_fifo0[6])
  );
  (* src = "contador.v:63" *)
  DFF _631_ (
    .C(clk),
    .D(_000_[7]),
    .Q(contador_fifo0[7])
  );
  (* src = "contador.v:63" *)
  DFF _632_ (
    .C(clk),
    .D(_000_[8]),
    .Q(contador_fifo0[8])
  );
  (* src = "contador.v:63" *)
  DFF _633_ (
    .C(clk),
    .D(_000_[9]),
    .Q(contador_fifo0[9])
  );
  (* src = "contador.v:63" *)
  DFF _634_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador_fifo1[0])
  );
  (* src = "contador.v:63" *)
  DFF _635_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador_fifo1[1])
  );
  (* src = "contador.v:63" *)
  DFF _636_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador_fifo1[2])
  );
  (* src = "contador.v:63" *)
  DFF _637_ (
    .C(clk),
    .D(_001_[3]),
    .Q(contador_fifo1[3])
  );
  (* src = "contador.v:63" *)
  DFF _638_ (
    .C(clk),
    .D(_001_[4]),
    .Q(contador_fifo1[4])
  );
  (* src = "contador.v:63" *)
  DFF _639_ (
    .C(clk),
    .D(_001_[5]),
    .Q(contador_fifo1[5])
  );
  (* src = "contador.v:63" *)
  DFF _640_ (
    .C(clk),
    .D(_001_[6]),
    .Q(contador_fifo1[6])
  );
  (* src = "contador.v:63" *)
  DFF _641_ (
    .C(clk),
    .D(_001_[7]),
    .Q(contador_fifo1[7])
  );
  (* src = "contador.v:63" *)
  DFF _642_ (
    .C(clk),
    .D(_001_[8]),
    .Q(contador_fifo1[8])
  );
  (* src = "contador.v:63" *)
  DFF _643_ (
    .C(clk),
    .D(_001_[9]),
    .Q(contador_fifo1[9])
  );
  (* src = "contador.v:63" *)
  DFF _644_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador_fifo2[0])
  );
  (* src = "contador.v:63" *)
  DFF _645_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador_fifo2[1])
  );
  (* src = "contador.v:63" *)
  DFF _646_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador_fifo2[2])
  );
  (* src = "contador.v:63" *)
  DFF _647_ (
    .C(clk),
    .D(_002_[3]),
    .Q(contador_fifo2[3])
  );
  (* src = "contador.v:63" *)
  DFF _648_ (
    .C(clk),
    .D(_002_[4]),
    .Q(contador_fifo2[4])
  );
  (* src = "contador.v:63" *)
  DFF _649_ (
    .C(clk),
    .D(_002_[5]),
    .Q(contador_fifo2[5])
  );
  (* src = "contador.v:63" *)
  DFF _650_ (
    .C(clk),
    .D(_002_[6]),
    .Q(contador_fifo2[6])
  );
  (* src = "contador.v:63" *)
  DFF _651_ (
    .C(clk),
    .D(_002_[7]),
    .Q(contador_fifo2[7])
  );
  (* src = "contador.v:63" *)
  DFF _652_ (
    .C(clk),
    .D(_002_[8]),
    .Q(contador_fifo2[8])
  );
  (* src = "contador.v:63" *)
  DFF _653_ (
    .C(clk),
    .D(_002_[9]),
    .Q(contador_fifo2[9])
  );
  (* src = "contador.v:63" *)
  DFF _654_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador_fifo3[0])
  );
  (* src = "contador.v:63" *)
  DFF _655_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador_fifo3[1])
  );
  (* src = "contador.v:63" *)
  DFF _656_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador_fifo3[2])
  );
  (* src = "contador.v:63" *)
  DFF _657_ (
    .C(clk),
    .D(_003_[3]),
    .Q(contador_fifo3[3])
  );
  (* src = "contador.v:63" *)
  DFF _658_ (
    .C(clk),
    .D(_003_[4]),
    .Q(contador_fifo3[4])
  );
  (* src = "contador.v:63" *)
  DFF _659_ (
    .C(clk),
    .D(_003_[5]),
    .Q(contador_fifo3[5])
  );
  (* src = "contador.v:63" *)
  DFF _660_ (
    .C(clk),
    .D(_003_[6]),
    .Q(contador_fifo3[6])
  );
  (* src = "contador.v:63" *)
  DFF _661_ (
    .C(clk),
    .D(_003_[7]),
    .Q(contador_fifo3[7])
  );
  (* src = "contador.v:63" *)
  DFF _662_ (
    .C(clk),
    .D(_003_[8]),
    .Q(contador_fifo3[8])
  );
  (* src = "contador.v:63" *)
  DFF _663_ (
    .C(clk),
    .D(_003_[9]),
    .Q(contador_fifo3[9])
  );
endmodule
