/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador.v:13" *)
module contador_s(clk, reset, idx, req, data_in_0, data_in_1, data_in_2, data_in_3, IDLE, valid_contador_s, contador_out_s);
  (* src = "contador.v:60" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _000_;
  (* src = "contador.v:60" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _001_;
  (* src = "contador.v:60" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _002_;
  (* src = "contador.v:60" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _003_;
  (* src = "contador.v:60" *)
  wire [4:0] _004_;
  (* src = "contador.v:60" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  (* src = "contador.v:31" *)
  input IDLE;
  (* src = "contador.v:22" *)
  input clk;
  (* src = "contador.v:50" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo0;
  (* src = "contador.v:51" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo1;
  (* src = "contador.v:52" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo2;
  (* src = "contador.v:53" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo3;
  (* src = "contador.v:35" *)
  output [4:0] contador_out_s;
  (* src = "contador.v:26" *)
  input [9:0] data_in_0;
  (* src = "contador.v:27" *)
  input [9:0] data_in_1;
  (* src = "contador.v:28" *)
  input [9:0] data_in_2;
  (* src = "contador.v:29" *)
  input [9:0] data_in_3;
  (* src = "contador.v:55" *)
  wire [9:0] data_vacio;
  (* src = "contador.v:24" *)
  input [2:0] idx;
  (* src = "contador.v:25" *)
  input req;
  (* src = "contador.v:23" *)
  input reset;
  (* src = "contador.v:34" *)
  output valid_contador_s;
  NOT _206_ (
    .A(idx[1]),
    .Y(_205_)
  );
  NOT _207_ (
    .A(idx[2]),
    .Y(_006_)
  );
  NOT _208_ (
    .A(idx[0]),
    .Y(_007_)
  );
  NOT _209_ (
    .A(req),
    .Y(_008_)
  );
  NOT _210_ (
    .A(IDLE),
    .Y(_009_)
  );
  NOT _211_ (
    .A(contador_fifo3[0]),
    .Y(_010_)
  );
  NOT _212_ (
    .A(contador_fifo3[1]),
    .Y(_011_)
  );
  NOT _213_ (
    .A(contador_fifo3[2]),
    .Y(_012_)
  );
  NOT _214_ (
    .A(contador_fifo3[3]),
    .Y(_013_)
  );
  NOT _215_ (
    .A(contador_fifo3[4]),
    .Y(_014_)
  );
  NOT _216_ (
    .A(reset),
    .Y(_015_)
  );
  NOT _217_ (
    .A(contador_fifo2[1]),
    .Y(_016_)
  );
  NOT _218_ (
    .A(contador_fifo2[3]),
    .Y(_017_)
  );
  NOT _219_ (
    .A(contador_fifo1[1]),
    .Y(_018_)
  );
  NOT _220_ (
    .A(contador_fifo1[3]),
    .Y(_019_)
  );
  NOT _221_ (
    .A(contador_fifo0[1]),
    .Y(_020_)
  );
  NOT _222_ (
    .A(contador_fifo0[3]),
    .Y(_021_)
  );
  NOT _223_ (
    .A(contador_out_s[0]),
    .Y(_022_)
  );
  NOT _224_ (
    .A(contador_out_s[2]),
    .Y(_023_)
  );
  NOT _225_ (
    .A(contador_out_s[3]),
    .Y(_024_)
  );
  NOR _226_ (
    .A(data_in_3[6]),
    .B(data_in_3[7]),
    .Y(_025_)
  );
  NOR _227_ (
    .A(data_in_3[8]),
    .B(data_in_3[9]),
    .Y(_026_)
  );
  NAND _228_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _229_ (
    .A(data_in_3[0]),
    .B(data_in_3[1]),
    .Y(_028_)
  );
  NOR _230_ (
    .A(data_in_3[3]),
    .B(data_in_3[4]),
    .Y(_029_)
  );
  NOR _231_ (
    .A(data_in_3[2]),
    .B(data_in_3[5]),
    .Y(_030_)
  );
  NAND _232_ (
    .A(_028_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _233_ (
    .A(_027_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _234_ (
    .A(_029_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _235_ (
    .A(contador_fifo3[0]),
    .B(_033_),
    .Y(_034_)
  );
  NOR _236_ (
    .A(contador_fifo3[0]),
    .B(_033_),
    .Y(_035_)
  );
  NOR _237_ (
    .A(reset),
    .B(_035_),
    .Y(_036_)
  );
  NAND _238_ (
    .A(_034_),
    .B(_036_),
    .Y(_037_)
  );
  NOT _239_ (
    .A(_037_),
    .Y(_003_[0])
  );
  NOR _240_ (
    .A(_011_),
    .B(_034_),
    .Y(_038_)
  );
  NAND _241_ (
    .A(_011_),
    .B(_034_),
    .Y(_039_)
  );
  NAND _242_ (
    .A(_015_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _243_ (
    .A(_038_),
    .B(_040_),
    .Y(_003_[1])
  );
  NAND _244_ (
    .A(contador_fifo3[2]),
    .B(_038_),
    .Y(_041_)
  );
  NOR _245_ (
    .A(contador_fifo3[2]),
    .B(_038_),
    .Y(_042_)
  );
  NAND _246_ (
    .A(_015_),
    .B(_041_),
    .Y(_043_)
  );
  NOR _247_ (
    .A(_042_),
    .B(_043_),
    .Y(_003_[2])
  );
  NOR _248_ (
    .A(_013_),
    .B(_041_),
    .Y(_044_)
  );
  NAND _249_ (
    .A(_013_),
    .B(_041_),
    .Y(_045_)
  );
  NAND _250_ (
    .A(_015_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _251_ (
    .A(_044_),
    .B(_046_),
    .Y(_003_[3])
  );
  NAND _252_ (
    .A(contador_fifo3[4]),
    .B(_044_),
    .Y(_047_)
  );
  NOR _253_ (
    .A(contador_fifo3[4]),
    .B(_044_),
    .Y(_048_)
  );
  NOR _254_ (
    .A(reset),
    .B(_048_),
    .Y(_049_)
  );
  NAND _255_ (
    .A(_047_),
    .B(_049_),
    .Y(_050_)
  );
  NOT _256_ (
    .A(_050_),
    .Y(_003_[4])
  );
  NOR _257_ (
    .A(data_in_2[6]),
    .B(data_in_2[7]),
    .Y(_051_)
  );
  NOR _258_ (
    .A(data_in_2[8]),
    .B(data_in_2[9]),
    .Y(_052_)
  );
  NAND _259_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _260_ (
    .A(data_in_2[0]),
    .B(data_in_2[1]),
    .Y(_054_)
  );
  NOR _261_ (
    .A(data_in_2[3]),
    .B(data_in_2[4]),
    .Y(_055_)
  );
  NOR _262_ (
    .A(data_in_2[2]),
    .B(data_in_2[5]),
    .Y(_056_)
  );
  NAND _263_ (
    .A(_054_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _264_ (
    .A(_053_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _265_ (
    .A(_055_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _266_ (
    .A(contador_fifo2[0]),
    .B(_059_),
    .Y(_060_)
  );
  NOR _267_ (
    .A(contador_fifo2[0]),
    .B(_059_),
    .Y(_061_)
  );
  NOR _268_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NAND _269_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  NOT _270_ (
    .A(_063_),
    .Y(_002_[0])
  );
  NOR _271_ (
    .A(_016_),
    .B(_060_),
    .Y(_064_)
  );
  NAND _272_ (
    .A(_016_),
    .B(_060_),
    .Y(_065_)
  );
  NAND _273_ (
    .A(_015_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _274_ (
    .A(_064_),
    .B(_066_),
    .Y(_002_[1])
  );
  NAND _275_ (
    .A(contador_fifo2[2]),
    .B(_064_),
    .Y(_067_)
  );
  NOR _276_ (
    .A(contador_fifo2[2]),
    .B(_064_),
    .Y(_068_)
  );
  NAND _277_ (
    .A(_015_),
    .B(_067_),
    .Y(_069_)
  );
  NOR _278_ (
    .A(_068_),
    .B(_069_),
    .Y(_002_[2])
  );
  NOR _279_ (
    .A(_017_),
    .B(_067_),
    .Y(_070_)
  );
  NAND _280_ (
    .A(_017_),
    .B(_067_),
    .Y(_071_)
  );
  NAND _281_ (
    .A(_015_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _282_ (
    .A(_070_),
    .B(_072_),
    .Y(_002_[3])
  );
  NAND _283_ (
    .A(contador_fifo2[4]),
    .B(_070_),
    .Y(_073_)
  );
  NOR _284_ (
    .A(contador_fifo2[4]),
    .B(_070_),
    .Y(_074_)
  );
  NOR _285_ (
    .A(reset),
    .B(_074_),
    .Y(_075_)
  );
  NAND _286_ (
    .A(_073_),
    .B(_075_),
    .Y(_076_)
  );
  NOT _287_ (
    .A(_076_),
    .Y(_002_[4])
  );
  NOR _288_ (
    .A(data_in_1[6]),
    .B(data_in_1[7]),
    .Y(_077_)
  );
  NOR _289_ (
    .A(data_in_1[8]),
    .B(data_in_1[9]),
    .Y(_078_)
  );
  NAND _290_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _291_ (
    .A(data_in_1[0]),
    .B(data_in_1[1]),
    .Y(_080_)
  );
  NOR _292_ (
    .A(data_in_1[3]),
    .B(data_in_1[4]),
    .Y(_081_)
  );
  NOR _293_ (
    .A(data_in_1[2]),
    .B(data_in_1[5]),
    .Y(_082_)
  );
  NAND _294_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _295_ (
    .A(_079_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _296_ (
    .A(_081_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _297_ (
    .A(contador_fifo1[0]),
    .B(_085_),
    .Y(_086_)
  );
  NOR _298_ (
    .A(contador_fifo1[0]),
    .B(_085_),
    .Y(_087_)
  );
  NOR _299_ (
    .A(reset),
    .B(_087_),
    .Y(_088_)
  );
  NAND _300_ (
    .A(_086_),
    .B(_088_),
    .Y(_089_)
  );
  NOT _301_ (
    .A(_089_),
    .Y(_001_[0])
  );
  NOR _302_ (
    .A(_018_),
    .B(_086_),
    .Y(_090_)
  );
  NAND _303_ (
    .A(_018_),
    .B(_086_),
    .Y(_091_)
  );
  NAND _304_ (
    .A(_015_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _305_ (
    .A(_090_),
    .B(_092_),
    .Y(_001_[1])
  );
  NAND _306_ (
    .A(contador_fifo1[2]),
    .B(_090_),
    .Y(_093_)
  );
  NOR _307_ (
    .A(contador_fifo1[2]),
    .B(_090_),
    .Y(_094_)
  );
  NAND _308_ (
    .A(_015_),
    .B(_093_),
    .Y(_095_)
  );
  NOR _309_ (
    .A(_094_),
    .B(_095_),
    .Y(_001_[2])
  );
  NOR _310_ (
    .A(_019_),
    .B(_093_),
    .Y(_096_)
  );
  NAND _311_ (
    .A(_019_),
    .B(_093_),
    .Y(_097_)
  );
  NAND _312_ (
    .A(_015_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _313_ (
    .A(_096_),
    .B(_098_),
    .Y(_001_[3])
  );
  NAND _314_ (
    .A(contador_fifo1[4]),
    .B(_096_),
    .Y(_099_)
  );
  NOR _315_ (
    .A(contador_fifo1[4]),
    .B(_096_),
    .Y(_100_)
  );
  NOR _316_ (
    .A(reset),
    .B(_100_),
    .Y(_101_)
  );
  NAND _317_ (
    .A(_099_),
    .B(_101_),
    .Y(_102_)
  );
  NOT _318_ (
    .A(_102_),
    .Y(_001_[4])
  );
  NOR _319_ (
    .A(data_in_0[8]),
    .B(data_in_0[9]),
    .Y(_103_)
  );
  NOR _320_ (
    .A(data_in_0[0]),
    .B(data_in_0[1]),
    .Y(_104_)
  );
  NAND _321_ (
    .A(_103_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _322_ (
    .A(data_in_0[2]),
    .B(data_in_0[3]),
    .Y(_106_)
  );
  NOR _323_ (
    .A(data_in_0[5]),
    .B(data_in_0[6]),
    .Y(_107_)
  );
  NOR _324_ (
    .A(data_in_0[4]),
    .B(data_in_0[7]),
    .Y(_108_)
  );
  NAND _325_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _326_ (
    .A(_105_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _327_ (
    .A(_107_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _328_ (
    .A(contador_fifo0[0]),
    .B(_111_),
    .Y(_112_)
  );
  NOR _329_ (
    .A(contador_fifo0[0]),
    .B(_111_),
    .Y(_113_)
  );
  NOR _330_ (
    .A(reset),
    .B(_113_),
    .Y(_114_)
  );
  NAND _331_ (
    .A(_112_),
    .B(_114_),
    .Y(_115_)
  );
  NOT _332_ (
    .A(_115_),
    .Y(_000_[0])
  );
  NOR _333_ (
    .A(_020_),
    .B(_112_),
    .Y(_116_)
  );
  NAND _334_ (
    .A(_020_),
    .B(_112_),
    .Y(_117_)
  );
  NAND _335_ (
    .A(_015_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _336_ (
    .A(_116_),
    .B(_118_),
    .Y(_000_[1])
  );
  NAND _337_ (
    .A(contador_fifo0[2]),
    .B(_116_),
    .Y(_119_)
  );
  NOR _338_ (
    .A(contador_fifo0[2]),
    .B(_116_),
    .Y(_120_)
  );
  NAND _339_ (
    .A(_015_),
    .B(_119_),
    .Y(_121_)
  );
  NOR _340_ (
    .A(_120_),
    .B(_121_),
    .Y(_000_[2])
  );
  NOR _341_ (
    .A(_021_),
    .B(_119_),
    .Y(_122_)
  );
  NAND _342_ (
    .A(_021_),
    .B(_119_),
    .Y(_123_)
  );
  NAND _343_ (
    .A(_015_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _344_ (
    .A(_122_),
    .B(_124_),
    .Y(_000_[3])
  );
  NAND _345_ (
    .A(contador_fifo0[4]),
    .B(_122_),
    .Y(_125_)
  );
  NOR _346_ (
    .A(contador_fifo0[4]),
    .B(_122_),
    .Y(_126_)
  );
  NOR _347_ (
    .A(reset),
    .B(_126_),
    .Y(_127_)
  );
  NAND _348_ (
    .A(_125_),
    .B(_127_),
    .Y(_128_)
  );
  NOT _349_ (
    .A(_128_),
    .Y(_000_[4])
  );
  NAND _350_ (
    .A(_205_),
    .B(_006_),
    .Y(_129_)
  );
  NOR _351_ (
    .A(_205_),
    .B(idx[2]),
    .Y(_130_)
  );
  NOT _352_ (
    .A(_130_),
    .Y(_131_)
  );
  NAND _353_ (
    .A(idx[0]),
    .B(_130_),
    .Y(_132_)
  );
  NOT _354_ (
    .A(_132_),
    .Y(_133_)
  );
  NOR _355_ (
    .A(_010_),
    .B(_132_),
    .Y(_134_)
  );
  NOR _356_ (
    .A(idx[0]),
    .B(_131_),
    .Y(_135_)
  );
  NAND _357_ (
    .A(contador_fifo2[0]),
    .B(_135_),
    .Y(_136_)
  );
  NOR _358_ (
    .A(_022_),
    .B(_130_),
    .Y(_137_)
  );
  NOR _359_ (
    .A(_134_),
    .B(_137_),
    .Y(_138_)
  );
  NAND _360_ (
    .A(_136_),
    .B(_138_),
    .Y(_139_)
  );
  NAND _361_ (
    .A(_129_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _362_ (
    .A(_007_),
    .B(_129_),
    .Y(_141_)
  );
  NAND _363_ (
    .A(contador_fifo1[0]),
    .B(_141_),
    .Y(_142_)
  );
  NOR _364_ (
    .A(_008_),
    .B(_009_),
    .Y(_143_)
  );
  NAND _365_ (
    .A(req),
    .B(IDLE),
    .Y(_144_)
  );
  NOR _366_ (
    .A(idx[0]),
    .B(_129_),
    .Y(_145_)
  );
  NAND _367_ (
    .A(contador_fifo0[0]),
    .B(_145_),
    .Y(_146_)
  );
  NAND _368_ (
    .A(_142_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _369_ (
    .A(_144_),
    .B(_147_),
    .Y(_148_)
  );
  NAND _370_ (
    .A(_140_),
    .B(_148_),
    .Y(_149_)
  );
  NOR _371_ (
    .A(contador_out_s[0]),
    .B(_143_),
    .Y(_150_)
  );
  NAND _372_ (
    .A(_015_),
    .B(_149_),
    .Y(_151_)
  );
  NOR _373_ (
    .A(_150_),
    .B(_151_),
    .Y(_004_[0])
  );
  NAND _374_ (
    .A(contador_fifo2[1]),
    .B(_135_),
    .Y(_152_)
  );
  NOT _375_ (
    .A(_152_),
    .Y(_153_)
  );
  NAND _376_ (
    .A(contador_fifo3[1]),
    .B(_133_),
    .Y(_154_)
  );
  NAND _377_ (
    .A(idx[2]),
    .B(contador_out_s[1]),
    .Y(_155_)
  );
  NAND _378_ (
    .A(_154_),
    .B(_155_),
    .Y(_156_)
  );
  NOR _379_ (
    .A(_153_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _380_ (
    .A(contador_fifo1[1]),
    .B(_141_),
    .Y(_158_)
  );
  NAND _381_ (
    .A(contador_fifo0[1]),
    .B(_145_),
    .Y(_159_)
  );
  NAND _382_ (
    .A(_158_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _383_ (
    .A(_144_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _384_ (
    .A(_157_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _385_ (
    .A(contador_out_s[1]),
    .B(_143_),
    .Y(_163_)
  );
  NAND _386_ (
    .A(_015_),
    .B(_162_),
    .Y(_164_)
  );
  NOR _387_ (
    .A(_163_),
    .B(_164_),
    .Y(_004_[1])
  );
  NOR _388_ (
    .A(_012_),
    .B(_132_),
    .Y(_165_)
  );
  NAND _389_ (
    .A(contador_fifo2[2]),
    .B(_135_),
    .Y(_166_)
  );
  NOR _390_ (
    .A(_023_),
    .B(_130_),
    .Y(_167_)
  );
  NOR _391_ (
    .A(_165_),
    .B(_167_),
    .Y(_168_)
  );
  NAND _392_ (
    .A(_166_),
    .B(_168_),
    .Y(_169_)
  );
  NAND _393_ (
    .A(_129_),
    .B(_169_),
    .Y(_170_)
  );
  NAND _394_ (
    .A(contador_fifo1[2]),
    .B(_141_),
    .Y(_171_)
  );
  NAND _395_ (
    .A(contador_fifo0[2]),
    .B(_145_),
    .Y(_172_)
  );
  NAND _396_ (
    .A(_171_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _397_ (
    .A(_144_),
    .B(_173_),
    .Y(_174_)
  );
  NAND _398_ (
    .A(_170_),
    .B(_174_),
    .Y(_175_)
  );
  NOR _399_ (
    .A(contador_out_s[2]),
    .B(_143_),
    .Y(_176_)
  );
  NAND _400_ (
    .A(_015_),
    .B(_175_),
    .Y(_177_)
  );
  NOR _401_ (
    .A(_176_),
    .B(_177_),
    .Y(_004_[2])
  );
  NOR _402_ (
    .A(_013_),
    .B(_132_),
    .Y(_178_)
  );
  NAND _403_ (
    .A(contador_fifo2[3]),
    .B(_135_),
    .Y(_179_)
  );
  NOR _404_ (
    .A(_024_),
    .B(_130_),
    .Y(_180_)
  );
  NOR _405_ (
    .A(_178_),
    .B(_180_),
    .Y(_181_)
  );
  NAND _406_ (
    .A(_179_),
    .B(_181_),
    .Y(_182_)
  );
  NAND _407_ (
    .A(_129_),
    .B(_182_),
    .Y(_183_)
  );
  NAND _408_ (
    .A(contador_fifo1[3]),
    .B(_141_),
    .Y(_184_)
  );
  NAND _409_ (
    .A(contador_fifo0[3]),
    .B(_145_),
    .Y(_185_)
  );
  NAND _410_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  NOR _411_ (
    .A(_144_),
    .B(_186_),
    .Y(_187_)
  );
  NAND _412_ (
    .A(_183_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _413_ (
    .A(contador_out_s[3]),
    .B(_143_),
    .Y(_189_)
  );
  NAND _414_ (
    .A(_015_),
    .B(_188_),
    .Y(_190_)
  );
  NOR _415_ (
    .A(_189_),
    .B(_190_),
    .Y(_004_[3])
  );
  NAND _416_ (
    .A(contador_fifo2[4]),
    .B(_135_),
    .Y(_191_)
  );
  NOR _417_ (
    .A(_014_),
    .B(_132_),
    .Y(_192_)
  );
  NAND _418_ (
    .A(idx[2]),
    .B(contador_out_s[4]),
    .Y(_193_)
  );
  NAND _419_ (
    .A(_191_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _420_ (
    .A(_192_),
    .B(_194_),
    .Y(_195_)
  );
  NAND _421_ (
    .A(contador_fifo1[4]),
    .B(_141_),
    .Y(_196_)
  );
  NAND _422_ (
    .A(contador_fifo0[4]),
    .B(_145_),
    .Y(_197_)
  );
  NAND _423_ (
    .A(_196_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _424_ (
    .A(_144_),
    .B(_198_),
    .Y(_199_)
  );
  NAND _425_ (
    .A(_195_),
    .B(_199_),
    .Y(_200_)
  );
  NOR _426_ (
    .A(contador_out_s[4]),
    .B(_143_),
    .Y(_201_)
  );
  NAND _427_ (
    .A(_015_),
    .B(_200_),
    .Y(_202_)
  );
  NOR _428_ (
    .A(_201_),
    .B(_202_),
    .Y(_004_[4])
  );
  NOR _429_ (
    .A(idx[2]),
    .B(_144_),
    .Y(_203_)
  );
  NOR _430_ (
    .A(valid_contador_s),
    .B(_203_),
    .Y(_204_)
  );
  NOR _431_ (
    .A(reset),
    .B(_204_),
    .Y(_005_)
  );
  (* src = "contador.v:60" *)
  DFF _432_ (
    .C(clk),
    .D(_005_),
    .Q(valid_contador_s)
  );
  (* src = "contador.v:60" *)
  DFF _433_ (
    .C(clk),
    .D(_004_[0]),
    .Q(contador_out_s[0])
  );
  (* src = "contador.v:60" *)
  DFF _434_ (
    .C(clk),
    .D(_004_[1]),
    .Q(contador_out_s[1])
  );
  (* src = "contador.v:60" *)
  DFF _435_ (
    .C(clk),
    .D(_004_[2]),
    .Q(contador_out_s[2])
  );
  (* src = "contador.v:60" *)
  DFF _436_ (
    .C(clk),
    .D(_004_[3]),
    .Q(contador_out_s[3])
  );
  (* src = "contador.v:60" *)
  DFF _437_ (
    .C(clk),
    .D(_004_[4]),
    .Q(contador_out_s[4])
  );
  (* src = "contador.v:60" *)
  DFF _438_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador_fifo0[0])
  );
  (* src = "contador.v:60" *)
  DFF _439_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador_fifo0[1])
  );
  (* src = "contador.v:60" *)
  DFF _440_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador_fifo0[2])
  );
  (* src = "contador.v:60" *)
  DFF _441_ (
    .C(clk),
    .D(_000_[3]),
    .Q(contador_fifo0[3])
  );
  (* src = "contador.v:60" *)
  DFF _442_ (
    .C(clk),
    .D(_000_[4]),
    .Q(contador_fifo0[4])
  );
  (* src = "contador.v:60" *)
  DFF _443_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador_fifo1[0])
  );
  (* src = "contador.v:60" *)
  DFF _444_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador_fifo1[1])
  );
  (* src = "contador.v:60" *)
  DFF _445_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador_fifo1[2])
  );
  (* src = "contador.v:60" *)
  DFF _446_ (
    .C(clk),
    .D(_001_[3]),
    .Q(contador_fifo1[3])
  );
  (* src = "contador.v:60" *)
  DFF _447_ (
    .C(clk),
    .D(_001_[4]),
    .Q(contador_fifo1[4])
  );
  (* src = "contador.v:60" *)
  DFF _448_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador_fifo2[0])
  );
  (* src = "contador.v:60" *)
  DFF _449_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador_fifo2[1])
  );
  (* src = "contador.v:60" *)
  DFF _450_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador_fifo2[2])
  );
  (* src = "contador.v:60" *)
  DFF _451_ (
    .C(clk),
    .D(_002_[3]),
    .Q(contador_fifo2[3])
  );
  (* src = "contador.v:60" *)
  DFF _452_ (
    .C(clk),
    .D(_002_[4]),
    .Q(contador_fifo2[4])
  );
  (* src = "contador.v:60" *)
  DFF _453_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador_fifo3[0])
  );
  (* src = "contador.v:60" *)
  DFF _454_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador_fifo3[1])
  );
  (* src = "contador.v:60" *)
  DFF _455_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador_fifo3[2])
  );
  (* src = "contador.v:60" *)
  DFF _456_ (
    .C(clk),
    .D(_003_[3]),
    .Q(contador_fifo3[3])
  );
  (* src = "contador.v:60" *)
  DFF _457_ (
    .C(clk),
    .D(_003_[4]),
    .Q(contador_fifo3[4])
  );
  assign data_vacio = 10'h000;
endmodule
