/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador.v:13" *)
module contador_s(clk, reset, idx, req, pop_F0, pop_F1, pop_F2, pop_F3, IDLE, valid_contador_s, contador_out_s, valid_contador_s_s, contador_out_s_s);
  (* src = "contador.v:61" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _000_;
  (* src = "contador.v:61" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _001_;
  (* src = "contador.v:61" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _002_;
  (* src = "contador.v:61" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] _003_;
  (* src = "contador.v:61" *)
  wire [4:0] _004_;
  (* src = "contador.v:61" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  (* src = "contador.v:31" *)
  input IDLE;
  (* src = "contador.v:22" *)
  input clk;
  (* src = "contador.v:51" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo0;
  (* src = "contador.v:52" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo1;
  (* src = "contador.v:53" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo2;
  (* src = "contador.v:54" *)
  (* unused_bits = "5 6 7 8 9" *)
  wire [9:0] contador_fifo3;
  (* src = "contador.v:35" *)
  output [4:0] contador_out_s;
  (* src = "contador.v:37" *)
  output [4:0] contador_out_s_s;
  (* src = "contador.v:24" *)
  input [1:0] idx;
  (* src = "contador.v:26" *)
  input pop_F0;
  (* src = "contador.v:27" *)
  input pop_F1;
  (* src = "contador.v:28" *)
  input pop_F2;
  (* src = "contador.v:29" *)
  input pop_F3;
  (* src = "contador.v:25" *)
  input req;
  (* src = "contador.v:23" *)
  input reset;
  (* src = "contador.v:34" *)
  output valid_contador_s;
  (* src = "contador.v:36" *)
  output valid_contador_s_s;
  NOT _182_ (
    .A(idx[0]),
    .Y(_146_)
  );
  NOT _183_ (
    .A(idx[1]),
    .Y(_147_)
  );
  NOT _184_ (
    .A(contador_fifo3[0]),
    .Y(_148_)
  );
  NOT _185_ (
    .A(pop_F3),
    .Y(_149_)
  );
  NOT _186_ (
    .A(contador_fifo3[1]),
    .Y(_150_)
  );
  NOT _187_ (
    .A(contador_fifo3[2]),
    .Y(_151_)
  );
  NOT _188_ (
    .A(contador_fifo3[4]),
    .Y(_152_)
  );
  NOT _189_ (
    .A(reset),
    .Y(_153_)
  );
  NOT _190_ (
    .A(contador_fifo2[0]),
    .Y(_154_)
  );
  NOT _191_ (
    .A(pop_F2),
    .Y(_155_)
  );
  NOT _192_ (
    .A(contador_fifo2[1]),
    .Y(_156_)
  );
  NOT _193_ (
    .A(contador_fifo2[2]),
    .Y(_157_)
  );
  NOT _194_ (
    .A(contador_fifo2[4]),
    .Y(_158_)
  );
  NOT _195_ (
    .A(contador_fifo1[0]),
    .Y(_159_)
  );
  NOT _196_ (
    .A(pop_F1),
    .Y(_160_)
  );
  NOT _197_ (
    .A(contador_fifo1[1]),
    .Y(_161_)
  );
  NOT _198_ (
    .A(contador_fifo1[2]),
    .Y(_162_)
  );
  NOT _199_ (
    .A(contador_fifo1[4]),
    .Y(_163_)
  );
  NOT _200_ (
    .A(contador_fifo0[0]),
    .Y(_164_)
  );
  NOT _201_ (
    .A(pop_F0),
    .Y(_165_)
  );
  NOT _202_ (
    .A(contador_fifo0[1]),
    .Y(_166_)
  );
  NOT _203_ (
    .A(contador_fifo0[2]),
    .Y(_167_)
  );
  NOT _204_ (
    .A(contador_fifo0[4]),
    .Y(_168_)
  );
  NOR _205_ (
    .A(_148_),
    .B(_149_),
    .Y(_169_)
  );
  NAND _206_ (
    .A(contador_fifo3[0]),
    .B(pop_F3),
    .Y(_170_)
  );
  NOR _207_ (
    .A(contador_fifo3[0]),
    .B(pop_F3),
    .Y(_171_)
  );
  NOR _208_ (
    .A(reset),
    .B(_171_),
    .Y(_172_)
  );
  NAND _209_ (
    .A(_170_),
    .B(_172_),
    .Y(_173_)
  );
  NOT _210_ (
    .A(_173_),
    .Y(_003_[0])
  );
  NOR _211_ (
    .A(_150_),
    .B(_170_),
    .Y(_174_)
  );
  NAND _212_ (
    .A(contador_fifo3[1]),
    .B(_169_),
    .Y(_175_)
  );
  NOR _213_ (
    .A(contador_fifo3[1]),
    .B(_169_),
    .Y(_176_)
  );
  NOR _214_ (
    .A(reset),
    .B(_176_),
    .Y(_177_)
  );
  NAND _215_ (
    .A(_175_),
    .B(_177_),
    .Y(_178_)
  );
  NOT _216_ (
    .A(_178_),
    .Y(_003_[1])
  );
  NOR _217_ (
    .A(_151_),
    .B(_175_),
    .Y(_179_)
  );
  NAND _218_ (
    .A(contador_fifo3[2]),
    .B(_174_),
    .Y(_180_)
  );
  NOR _219_ (
    .A(contador_fifo3[2]),
    .B(_174_),
    .Y(_181_)
  );
  NOR _220_ (
    .A(reset),
    .B(_181_),
    .Y(_006_)
  );
  NAND _221_ (
    .A(_180_),
    .B(_006_),
    .Y(_007_)
  );
  NOT _222_ (
    .A(_007_),
    .Y(_003_[2])
  );
  NAND _223_ (
    .A(contador_fifo3[3]),
    .B(_179_),
    .Y(_008_)
  );
  NOR _224_ (
    .A(contador_fifo3[3]),
    .B(_179_),
    .Y(_009_)
  );
  NOR _225_ (
    .A(reset),
    .B(_009_),
    .Y(_010_)
  );
  NAND _226_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOT _227_ (
    .A(_011_),
    .Y(_003_[3])
  );
  NOR _228_ (
    .A(_152_),
    .B(_008_),
    .Y(_012_)
  );
  NAND _229_ (
    .A(_152_),
    .B(_008_),
    .Y(_013_)
  );
  NAND _230_ (
    .A(_153_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _231_ (
    .A(_012_),
    .B(_014_),
    .Y(_003_[4])
  );
  NOR _232_ (
    .A(_154_),
    .B(_155_),
    .Y(_015_)
  );
  NAND _233_ (
    .A(contador_fifo2[0]),
    .B(pop_F2),
    .Y(_016_)
  );
  NOR _234_ (
    .A(contador_fifo2[0]),
    .B(pop_F2),
    .Y(_017_)
  );
  NOR _235_ (
    .A(reset),
    .B(_017_),
    .Y(_018_)
  );
  NAND _236_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NOT _237_ (
    .A(_019_),
    .Y(_002_[0])
  );
  NOR _238_ (
    .A(_156_),
    .B(_016_),
    .Y(_020_)
  );
  NAND _239_ (
    .A(contador_fifo2[1]),
    .B(_015_),
    .Y(_021_)
  );
  NOR _240_ (
    .A(contador_fifo2[1]),
    .B(_015_),
    .Y(_022_)
  );
  NOR _241_ (
    .A(reset),
    .B(_022_),
    .Y(_023_)
  );
  NAND _242_ (
    .A(_021_),
    .B(_023_),
    .Y(_024_)
  );
  NOT _243_ (
    .A(_024_),
    .Y(_002_[1])
  );
  NOR _244_ (
    .A(_157_),
    .B(_021_),
    .Y(_025_)
  );
  NAND _245_ (
    .A(contador_fifo2[2]),
    .B(_020_),
    .Y(_026_)
  );
  NOR _246_ (
    .A(contador_fifo2[2]),
    .B(_020_),
    .Y(_027_)
  );
  NOR _247_ (
    .A(reset),
    .B(_027_),
    .Y(_028_)
  );
  NAND _248_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  NOT _249_ (
    .A(_029_),
    .Y(_002_[2])
  );
  NAND _250_ (
    .A(contador_fifo2[3]),
    .B(_025_),
    .Y(_030_)
  );
  NOR _251_ (
    .A(contador_fifo2[3]),
    .B(_025_),
    .Y(_031_)
  );
  NOR _252_ (
    .A(reset),
    .B(_031_),
    .Y(_032_)
  );
  NAND _253_ (
    .A(_030_),
    .B(_032_),
    .Y(_033_)
  );
  NOT _254_ (
    .A(_033_),
    .Y(_002_[3])
  );
  NOR _255_ (
    .A(_158_),
    .B(_030_),
    .Y(_034_)
  );
  NAND _256_ (
    .A(_158_),
    .B(_030_),
    .Y(_035_)
  );
  NAND _257_ (
    .A(_153_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _258_ (
    .A(_034_),
    .B(_036_),
    .Y(_002_[4])
  );
  NOR _259_ (
    .A(_159_),
    .B(_160_),
    .Y(_037_)
  );
  NAND _260_ (
    .A(contador_fifo1[0]),
    .B(pop_F1),
    .Y(_038_)
  );
  NOR _261_ (
    .A(contador_fifo1[0]),
    .B(pop_F1),
    .Y(_039_)
  );
  NOR _262_ (
    .A(reset),
    .B(_039_),
    .Y(_040_)
  );
  NAND _263_ (
    .A(_038_),
    .B(_040_),
    .Y(_041_)
  );
  NOT _264_ (
    .A(_041_),
    .Y(_001_[0])
  );
  NOR _265_ (
    .A(_161_),
    .B(_038_),
    .Y(_042_)
  );
  NAND _266_ (
    .A(contador_fifo1[1]),
    .B(_037_),
    .Y(_043_)
  );
  NOR _267_ (
    .A(contador_fifo1[1]),
    .B(_037_),
    .Y(_044_)
  );
  NOR _268_ (
    .A(reset),
    .B(_044_),
    .Y(_045_)
  );
  NAND _269_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NOT _270_ (
    .A(_046_),
    .Y(_001_[1])
  );
  NOR _271_ (
    .A(_162_),
    .B(_043_),
    .Y(_047_)
  );
  NAND _272_ (
    .A(contador_fifo1[2]),
    .B(_042_),
    .Y(_048_)
  );
  NOR _273_ (
    .A(contador_fifo1[2]),
    .B(_042_),
    .Y(_049_)
  );
  NOR _274_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NAND _275_ (
    .A(_048_),
    .B(_050_),
    .Y(_051_)
  );
  NOT _276_ (
    .A(_051_),
    .Y(_001_[2])
  );
  NAND _277_ (
    .A(contador_fifo1[3]),
    .B(_047_),
    .Y(_052_)
  );
  NOR _278_ (
    .A(contador_fifo1[3]),
    .B(_047_),
    .Y(_053_)
  );
  NOR _279_ (
    .A(reset),
    .B(_053_),
    .Y(_054_)
  );
  NAND _280_ (
    .A(_052_),
    .B(_054_),
    .Y(_055_)
  );
  NOT _281_ (
    .A(_055_),
    .Y(_001_[3])
  );
  NOR _282_ (
    .A(_163_),
    .B(_052_),
    .Y(_056_)
  );
  NAND _283_ (
    .A(_163_),
    .B(_052_),
    .Y(_057_)
  );
  NAND _284_ (
    .A(_153_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _285_ (
    .A(_056_),
    .B(_058_),
    .Y(_001_[4])
  );
  NOR _286_ (
    .A(_164_),
    .B(_165_),
    .Y(_059_)
  );
  NAND _287_ (
    .A(contador_fifo0[0]),
    .B(pop_F0),
    .Y(_060_)
  );
  NOR _288_ (
    .A(contador_fifo0[0]),
    .B(pop_F0),
    .Y(_061_)
  );
  NOR _289_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NAND _290_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  NOT _291_ (
    .A(_063_),
    .Y(_000_[0])
  );
  NOR _292_ (
    .A(_166_),
    .B(_060_),
    .Y(_064_)
  );
  NAND _293_ (
    .A(contador_fifo0[1]),
    .B(_059_),
    .Y(_065_)
  );
  NOR _294_ (
    .A(contador_fifo0[1]),
    .B(_059_),
    .Y(_066_)
  );
  NOR _295_ (
    .A(reset),
    .B(_066_),
    .Y(_067_)
  );
  NAND _296_ (
    .A(_065_),
    .B(_067_),
    .Y(_068_)
  );
  NOT _297_ (
    .A(_068_),
    .Y(_000_[1])
  );
  NOR _298_ (
    .A(_167_),
    .B(_065_),
    .Y(_069_)
  );
  NAND _299_ (
    .A(contador_fifo0[2]),
    .B(_064_),
    .Y(_070_)
  );
  NOR _300_ (
    .A(contador_fifo0[2]),
    .B(_064_),
    .Y(_071_)
  );
  NOR _301_ (
    .A(reset),
    .B(_071_),
    .Y(_072_)
  );
  NAND _302_ (
    .A(_070_),
    .B(_072_),
    .Y(_073_)
  );
  NOT _303_ (
    .A(_073_),
    .Y(_000_[2])
  );
  NAND _304_ (
    .A(contador_fifo0[3]),
    .B(_069_),
    .Y(_074_)
  );
  NOR _305_ (
    .A(contador_fifo0[3]),
    .B(_069_),
    .Y(_075_)
  );
  NOR _306_ (
    .A(reset),
    .B(_075_),
    .Y(_076_)
  );
  NAND _307_ (
    .A(_074_),
    .B(_076_),
    .Y(_077_)
  );
  NOT _308_ (
    .A(_077_),
    .Y(_000_[3])
  );
  NOR _309_ (
    .A(_168_),
    .B(_074_),
    .Y(_078_)
  );
  NAND _310_ (
    .A(_168_),
    .B(_074_),
    .Y(_079_)
  );
  NAND _311_ (
    .A(_153_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _312_ (
    .A(_078_),
    .B(_080_),
    .Y(_000_[4])
  );
  NAND _313_ (
    .A(req),
    .B(IDLE),
    .Y(_081_)
  );
  NOR _314_ (
    .A(_146_),
    .B(_147_),
    .Y(_082_)
  );
  NAND _315_ (
    .A(contador_fifo3[0]),
    .B(_082_),
    .Y(_083_)
  );
  NOR _316_ (
    .A(idx[0]),
    .B(_147_),
    .Y(_084_)
  );
  NAND _317_ (
    .A(contador_fifo2[0]),
    .B(_084_),
    .Y(_085_)
  );
  NAND _318_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _319_ (
    .A(idx[0]),
    .B(idx[1]),
    .Y(_087_)
  );
  NAND _320_ (
    .A(contador_fifo0[0]),
    .B(_087_),
    .Y(_088_)
  );
  NOR _321_ (
    .A(_146_),
    .B(idx[1]),
    .Y(_089_)
  );
  NAND _322_ (
    .A(contador_fifo1[0]),
    .B(_089_),
    .Y(_090_)
  );
  NAND _323_ (
    .A(_088_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _324_ (
    .A(_086_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _325_ (
    .A(_081_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _326_ (
    .A(contador_out_s[0]),
    .B(_081_),
    .Y(_094_)
  );
  NOT _327_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _328_ (
    .A(_093_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _329_ (
    .A(reset),
    .B(_096_),
    .Y(_004_[0])
  );
  NAND _330_ (
    .A(contador_fifo3[1]),
    .B(_082_),
    .Y(_097_)
  );
  NAND _331_ (
    .A(contador_fifo1[1]),
    .B(_089_),
    .Y(_098_)
  );
  NAND _332_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _333_ (
    .A(contador_fifo0[1]),
    .B(_087_),
    .Y(_100_)
  );
  NAND _334_ (
    .A(contador_fifo2[1]),
    .B(_084_),
    .Y(_101_)
  );
  NAND _335_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _336_ (
    .A(_099_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _337_ (
    .A(_081_),
    .B(_103_),
    .Y(_104_)
  );
  NAND _338_ (
    .A(contador_out_s[1]),
    .B(_081_),
    .Y(_105_)
  );
  NOT _339_ (
    .A(_105_),
    .Y(_106_)
  );
  NOR _340_ (
    .A(_104_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _341_ (
    .A(reset),
    .B(_107_),
    .Y(_004_[1])
  );
  NAND _342_ (
    .A(contador_fifo3[2]),
    .B(_082_),
    .Y(_108_)
  );
  NAND _343_ (
    .A(contador_fifo1[2]),
    .B(_089_),
    .Y(_109_)
  );
  NAND _344_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _345_ (
    .A(contador_fifo0[2]),
    .B(_087_),
    .Y(_111_)
  );
  NAND _346_ (
    .A(contador_fifo2[2]),
    .B(_084_),
    .Y(_112_)
  );
  NAND _347_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _348_ (
    .A(_110_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _349_ (
    .A(_081_),
    .B(_114_),
    .Y(_115_)
  );
  NAND _350_ (
    .A(contador_out_s[2]),
    .B(_081_),
    .Y(_116_)
  );
  NOT _351_ (
    .A(_116_),
    .Y(_117_)
  );
  NOR _352_ (
    .A(_115_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _353_ (
    .A(reset),
    .B(_118_),
    .Y(_004_[2])
  );
  NAND _354_ (
    .A(contador_fifo3[3]),
    .B(_082_),
    .Y(_119_)
  );
  NAND _355_ (
    .A(contador_fifo2[3]),
    .B(_084_),
    .Y(_120_)
  );
  NAND _356_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NAND _357_ (
    .A(contador_fifo0[3]),
    .B(_087_),
    .Y(_122_)
  );
  NAND _358_ (
    .A(contador_fifo1[3]),
    .B(_089_),
    .Y(_123_)
  );
  NAND _359_ (
    .A(_122_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _360_ (
    .A(_121_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _361_ (
    .A(_081_),
    .B(_125_),
    .Y(_126_)
  );
  NAND _362_ (
    .A(contador_out_s[3]),
    .B(_081_),
    .Y(_127_)
  );
  NOT _363_ (
    .A(_127_),
    .Y(_128_)
  );
  NOR _364_ (
    .A(_126_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _365_ (
    .A(reset),
    .B(_129_),
    .Y(_004_[3])
  );
  NAND _366_ (
    .A(contador_fifo3[4]),
    .B(_082_),
    .Y(_130_)
  );
  NAND _367_ (
    .A(contador_fifo1[4]),
    .B(_089_),
    .Y(_131_)
  );
  NAND _368_ (
    .A(_130_),
    .B(_131_),
    .Y(_132_)
  );
  NAND _369_ (
    .A(contador_fifo0[4]),
    .B(_087_),
    .Y(_133_)
  );
  NAND _370_ (
    .A(contador_fifo2[4]),
    .B(_084_),
    .Y(_134_)
  );
  NAND _371_ (
    .A(_133_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _372_ (
    .A(_132_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _373_ (
    .A(_081_),
    .B(_136_),
    .Y(_137_)
  );
  NAND _374_ (
    .A(contador_out_s[4]),
    .B(_081_),
    .Y(_138_)
  );
  NOT _375_ (
    .A(_138_),
    .Y(_139_)
  );
  NOR _376_ (
    .A(_137_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _377_ (
    .A(reset),
    .B(_140_),
    .Y(_004_[4])
  );
  NOR _378_ (
    .A(pop_F1),
    .B(valid_contador_s),
    .Y(_141_)
  );
  NAND _379_ (
    .A(_165_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _380_ (
    .A(pop_F3),
    .B(pop_F2),
    .Y(_143_)
  );
  NAND _381_ (
    .A(_081_),
    .B(_143_),
    .Y(_144_)
  );
  NOR _382_ (
    .A(_142_),
    .B(_144_),
    .Y(_145_)
  );
  NOR _383_ (
    .A(reset),
    .B(_145_),
    .Y(_005_)
  );
  (* src = "contador.v:61" *)
  DFF _384_ (
    .C(clk),
    .D(_005_),
    .Q(valid_contador_s)
  );
  (* src = "contador.v:61" *)
  DFF _385_ (
    .C(clk),
    .D(_004_[0]),
    .Q(contador_out_s[0])
  );
  (* src = "contador.v:61" *)
  DFF _386_ (
    .C(clk),
    .D(_004_[1]),
    .Q(contador_out_s[1])
  );
  (* src = "contador.v:61" *)
  DFF _387_ (
    .C(clk),
    .D(_004_[2]),
    .Q(contador_out_s[2])
  );
  (* src = "contador.v:61" *)
  DFF _388_ (
    .C(clk),
    .D(_004_[3]),
    .Q(contador_out_s[3])
  );
  (* src = "contador.v:61" *)
  DFF _389_ (
    .C(clk),
    .D(_004_[4]),
    .Q(contador_out_s[4])
  );
  (* src = "contador.v:61" *)
  DFF _390_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador_fifo0[0])
  );
  (* src = "contador.v:61" *)
  DFF _391_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador_fifo0[1])
  );
  (* src = "contador.v:61" *)
  DFF _392_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador_fifo0[2])
  );
  (* src = "contador.v:61" *)
  DFF _393_ (
    .C(clk),
    .D(_000_[3]),
    .Q(contador_fifo0[3])
  );
  (* src = "contador.v:61" *)
  DFF _394_ (
    .C(clk),
    .D(_000_[4]),
    .Q(contador_fifo0[4])
  );
  (* src = "contador.v:61" *)
  DFF _395_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador_fifo1[0])
  );
  (* src = "contador.v:61" *)
  DFF _396_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador_fifo1[1])
  );
  (* src = "contador.v:61" *)
  DFF _397_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador_fifo1[2])
  );
  (* src = "contador.v:61" *)
  DFF _398_ (
    .C(clk),
    .D(_001_[3]),
    .Q(contador_fifo1[3])
  );
  (* src = "contador.v:61" *)
  DFF _399_ (
    .C(clk),
    .D(_001_[4]),
    .Q(contador_fifo1[4])
  );
  (* src = "contador.v:61" *)
  DFF _400_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador_fifo2[0])
  );
  (* src = "contador.v:61" *)
  DFF _401_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador_fifo2[1])
  );
  (* src = "contador.v:61" *)
  DFF _402_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador_fifo2[2])
  );
  (* src = "contador.v:61" *)
  DFF _403_ (
    .C(clk),
    .D(_002_[3]),
    .Q(contador_fifo2[3])
  );
  (* src = "contador.v:61" *)
  DFF _404_ (
    .C(clk),
    .D(_002_[4]),
    .Q(contador_fifo2[4])
  );
  (* src = "contador.v:61" *)
  DFF _405_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador_fifo3[0])
  );
  (* src = "contador.v:61" *)
  DFF _406_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador_fifo3[1])
  );
  (* src = "contador.v:61" *)
  DFF _407_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador_fifo3[2])
  );
  (* src = "contador.v:61" *)
  DFF _408_ (
    .C(clk),
    .D(_003_[3]),
    .Q(contador_fifo3[3])
  );
  (* src = "contador.v:61" *)
  DFF _409_ (
    .C(clk),
    .D(_003_[4]),
    .Q(contador_fifo3[4])
  );
endmodule
